version: '3'
services:
  mysql:
      image: mysql:8.0.30
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
